name: aria_remote
description: "Aria Remote"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  clipboard: ^0.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  forui: ^0.10.0+1
  get: ^4.7.2
  google_fonts: ^6.2.1
  http: ^1.3.0
  loading_animation_widget: ^1.3.0
  package_info_plus: ^8.3.0
  path: ^1.9.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/